### PR TITLE
Some minor AI and sound improvements

### PR DESCRIPTION
**Pull request by siobhan-saoirse**
This fork adds some sound prefixes to the NPC sound effects, and some minor changes to the AI.

You're welcome by the way.

### CODE REVIEW

**Comment by DrVrej** [comment]
Hello, I am wondering what the purpose of the character '^' is? I have never seen that used before.

**Comment by Seamusmario** [comment]
https://developer.valvesoftware.com/wiki/Soundscripts

**Comment by Seamusmario** [comment]
Basically, the '^' character is used for distances, If far away, it switches to the right channel. If really close, it switches to the left channel.
One example would be hearing distant gunfire sounds. The sounds you put in for these NPCs are stereo.

**Comment by Seamusmario** [comment]
> https://developer.valvesoftware.com/wiki/Soundscripts

You can read more about it at the Source SDK Wiki.

**Comment by DrVrej** [comment]
Alright I will let @Cpt-Hazama decide what to do here as he is the owner of this expansion pack.

**Pull request closed without merging**
